### ISSUE TITLE
[WebAmoozWarningList] Dead domains

### ISSUE THREAD

**Issue by MasterKia** [MasterKia/PersianBlocker#118]
من صرفا چند مورد رو چک کردم.
سایت‌های زیر به نظر میاد واگذار شدند
```
Liyamtoken.com
https://unifunds.com/
mrdigicoin.eu
Hamyarminer.net
coin-hash.com
impero.solutions
```
این سایت‌ها بالا نمیان و بعضی شون حتی رکورد DNS ندارند. ولی حتما نمیتونم بگم که دیگه کار نمیکنند.

```
https://asaccoin.com/
https://wiseling.com/
https://mrdigicoin.io/
mrdigicoin.org
https://ai.marketing/
http://icbroker.com/
https://pcoinglobal.com/
```

**Comment by mmrabbani** [comment]
با سلام

لیست  دامنه ها را در سایت‌های فروش دامین چک کردم. دامنه های زیر دیگه آزاد و در سایت godaddy یا namecheap قابل خریداری توسط عموم هستند. این یعنی مالک قبلی تمدید نکرده است. لذا میتوانند از لیست حذف شوند. (این سایت ها دامنه ir رو پشتیبانی نمیکردند و لذا آنها چک نشدند)

coinohit.com
healour.com
imsmining.com
behkamcoin.com
coin-hash.com
impero.solutions
coinsmining.energy
farda.exchange
traderbully.com
