### ISSUE TITLE
pedal.ir

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#13]
https://user-images.githubusercontent.com/55192376/178767144-081697fb-b9da-4b3c-9f0a-a953c501bfc1.png

**Comment by MasterKia** [comment]
درود بر شما .
سعی کردم یه فیلتری اعمال کنم که _همه_ تبلیغاتِ متحرک حال و آینده رو پوشش بده، امیدوارم در آینده چیزی اشتباه پنهان سازی نشه.
سپاس از گزارش.

**Comment by sepehr-brj** [comment]
بریو این فیلتری که گذاشتید رو پشتیبانی نمیکنه.

میتونید فیلتری بذارید که بریو هم پشتیبانی کنه؟ یا نهایتش یه فیلتر نتورک میذارید تا گیف دانلود نشه؟

**Comment by sepehr-brj** [comment]
ممنونم

برای خودم نیست، امروز یه چند نفر پیدا کردم که براشون اهمیت داره. ولی اکثرا از بریو استفاده میکنن. هیچکس هم از فایرفاکس خوشش نمیاد.

این اولین گزارشیه که اطلاع دادن. فعلا گروه شما رو بهشون معرفی نمیکنم تا همونجا گزارش بدن و دیگران‌هم ببینن شاید علاقه‌مند شدن.

بعد که گزارش‌هاشون زیاد شد میارمشون گروه.
