### ISSUE TITLE
imna.ir

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#14]
روز بخیر
لطفا فیلترهای لازم رو برای این سایت اضافه کنید.

**Comment by MasterKia** [comment]
درود بر شما.
5 دقیقه دیگه لیست رو بروز کنید و ببینید آیا فیلتر ها برای مرورگر گوشی هم کافی هستن.
سپاس از گزارش.

**Comment by sepehr-brj** [comment]
ممنون از پیگیریتون
بله برای گوشی هم کافی هستن فیلتر‌ها

تبلیغاتی که بلاک میشن صرفا پنهان میشن یا میشه جلوی دانلودشون رو هم گرفت؟

**Comment by MasterKia** [comment]
انگار به خاطر این فیلتر جلوی دانلودشون هم گرفته شده:
`imna.ir##[href^="/redirect/ads/"]`

چون اگه مسدودساز رو خاموش کنید و Logger رو باز کنید آدرس یه سری تبلیغات که تهشون gif. داره میشه دید:
`https://media.imna.ir/d/2022/06/26/0/1794247.gif`

اما اگه مسدودساز رو روشن کنید دیگه آدرس هایی مانند اون توی Logger نشون داده نمیشن.
