### ISSUE TITLE
[Ad Report] honarehzendegi.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#18]
```
||honarehzendegi.com/resources/files/Ui/fixbar.gif$image
||honarehzendegi.com/resources/files/Ui/1.gif$image
||honarehzendegi.com/resources/files/Ui/2.gif$image
||honarehzendegi.com/resources/files/1400/new%20project(1).gif$image
honarehzendegi.com##.text-center.col-12
```

**Comment by MasterKia** [comment]
درود بر شما.
مواردی که فرستادید رو بررسی کردم،‌ اینا خود-تبلیغی (Self-Promotion) هستن یعنی سایت داره تبلیغ خودش رو میکنه و طبق خط مشی و سیاست های EasyList (که uBlock Origin هم ازش پیروی میکنه)، ما موارد خود-تبلیغی رو مسدود/پنهان نمیکنیم مگر اینکه خیلی رو مخ و آزاردهنده باشن (مثلاً نصف صفحه رو بگیرن،‌ تا نبندیشون نتونی مطلب اصلی رو ببینی،‌ حالت پاپ آپ داشته باشن و ..).
حالا اگه از نظر شما این خود-تبلیغی ها آزاردهنده حساب میشن باید یه فکری به حالشون کرد.

این سایت یک ردیاب (Fingerprinting) داشت که مسدودش کردم.

سپاس از گزارش.

**Comment by chromer030** [comment]
کاملا حق با شماست ، و ممنون از جواب خوبتون.
