### ISSUE TITLE
digiato.com

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#20]
موارد این سایت توی ایشوی جداگانه باشه تا تعداد لینک‌های بالای فیلترهاش بیشتر از یکی نشه بنظرم بهتره.

در مورد فضاهای خالی بعضی از کاربرهاش گفته بودن قالب جدید براشون سردرگمی ایجاد میکنه. بخاطر همین گفتم ممکنه فشردگی مطالب بدترش بکنه که خب بنظر خودم فرقی نداره.

فیلترهای فضای خالی رو اینطور بذارین مشکلی پیش نمیاد؟
```
!#if !env_mobile
digiato.com##.homeMainBanner
!#endif
!#if env_mobile
digiato.com##.digiBannerMobile
!#endif
```
چون تگ `‎##.digiBannerMobile` فضاهای خالی بیشتری رو توی حالت موبایل پنهان میکنه.

**Comment by MasterKia** [comment]
> در مورد فضاهای خالی بعضی از کاربرهاش گفته بودن قالب جدید براشون سردرگمی ایجاد میکنه.

من همه دیدگاه های [این صفحه](https://digiato.com/article/2022/07/25/digiato-redesign-new-site) رو خوندم و فقط سه نفر درباره فضای خالی چیزی گفته بودن (دو نفر گفتن فضای خالی زیادیه و یه نفرم گفته بود فضای خالی سفید چشمو اذیت میکنه).

اون فیلتر هم افزوده شد.

**Comment by sepehr-brj** [comment]
اون تگ `‎##.homeMainBanner` توی موبایل غیرفعال بشه بهتر نیست؟
چون با وجود `‎##.digiBannerMobile` دیگه نیازی بهش نیست.

**Comment by MasterKia** [comment]
از نظر بهینگی فرقی نداره چون حتی اگه شرط هم بذاریم، اونوقت افزونه افزونه باید اون شرط مربوط به homeMainBanner رو بررسی کنه به جای اعمال کردن خود فیلتر.

**Comment by sepehr-brj** [comment]
خب پس وقتی که فیلترهای مخصوص دسکتاپ زیاد باشه باید شرط رو گذاشت.

**Comment by MasterKia** [comment]
ضمناً مشکل دیگه ای هست، AdGuard کلا فیلتر های بین شرط env_mobile رو نادیده میگیره (باگ).
اگه اون فیلتری که اشاره کردید بره توی اون شرط، دیگه از دید AdGuard انگار وجود خارجی نداره.

**Comment by sepehr-brj** [comment]
کلا ادگارد چه برتری نسبت به uBO داره؟

**Comment by MasterKia** [comment]
پر زرق و برق تره. محصولات بیشتری هم داره (نرم افزار کامپیوتر، نرم افزار اندروید، DNS، اگه اشتباه نکنم VPN و ...)
توی ایشو های ریپوی ادگارد هم اگه نگاه کنید چندین ایشو از سایت های پارسی زبان هست پس ادگارد بین کاربران ایرانی کاربر داره و باید به فکر اون هم بود.

**Comment by MasterKia** [comment]
اما افزونه ها از نظر امکانات تقریباً با هم برابرند (به جز یه سری فیلتر ها که ادگارد فیلتر های بیشتری رو پشتیبانی میکنه و قدرت عمل بهتری میده. ضمناً ادگارد از فیلتر های جاوااسکریپتی خالص پشتیبانی داره یعنی میشه کد جاوااسکریپت نوشت که توی صفحه اجرا بشه اما uBO به دلایل امنیتی فعلا این قابلیت رو نذاشته.)

از نظر بهینگی uBO بهتره.
