### ISSUE TITLE
[Ad Report] ilna.ir

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#22]
با سلام و خسته نباشید و تشکر ، این سایت انبوهی از تبلیغات رو نشون میده.

**Comment by MasterKia** [comment]
درود بر شما، درست شد.

سپاس از گزارش.

چون سمت چپ سایت فضای تبلیغات بود، مطالب اصلی متمایل به راست بودن. بنابراین یکم مطالب سایت رو شیفت دادم به سمت چپ.
توی گوشی و کامپیوتر اگه تونستید بررسی کنید ببینید سایت بدشکل نشده باشه.
@sepehr-brj

**Comment by MasterKia** [comment]
توی گوشی بدشکل میشد تنظیم کردم فقط توی کامپیوتر اعمال بشه.

**Comment by chromer030** [comment]
درود فراوان بر شما و تشکر از زحمات شما.

**Comment by sepehr-brj** [comment]
> چون سمت چپ سایت فضای تبلیغات بود، مطالب اصلی متمایل به راست بودن. بنابراین یکم مطالب سایت رو شیفت دادم به سمت چپ.
توی گوشی و کامپیوتر اگه تونستید بررسی کنید ببینید سایت بدشکل نشده باشه.

بسیار عالی

‌
- پسوند دامنه‌ی این سایت از `‎.news` به `‎.ir` تغییر داده شده، پس به فیلترهای مربوط به `ilna.news` دیگه نیازی نیست.
‏
‏
- این فیلتر رو برای حالت موبایل اضافه کنید:
‏`ilna.ir##.zxc-mobile`
‏
‏
- فیلتر `‎||ilna.ir/servev2/‎` رو بجای فیلتر `‎||ilna.ir/servev2/*.gif` بذارین تا عکس‌ها هم دانلود نشن مشکلی پیش نمیاد؟
‏
‏
- وارد یکی از اخبار این سایت که بشید بعد از چند ثانیه بالای خبر یه تبلیغ ویدیویی بارگزاری میشه که البته با فیلتر `‎##.zxc` که گذاشتین پنهان میشه.
آیا از دانلود این ویدیوها جلوگیری هم میشه؟

‌
> توی گوشی بدشکل میشد تنظیم کردم فقط توی کامپیوتر اعمال بشه.

هنوز هم یه مقدار فضای خالی مونده. اگه اون فیلتر رو بتونید تغییراتی بدین تا اون فضای خالی کامل از بین بره احتمالا دیگه برای حالت موبایل هم مشکلی نداشته باشه. (بخاطر این میگم تا بشه از این فیلتر توی تبلت هم استفاده بشه، ولی اگه نمیشه خب مشکلی نیست)

**Comment by MasterKia** [comment]
> * فیلتر `‎||ilna.ir/servev2/‎` رو بجای فیلتر `‎||ilna.ir/servev2/*.gif` بذارین تا عکس‌ها هم دانلود نشن مشکلی پیش نمیاد؟

اون وقت عکس های این صفحه مسدود میشن:
`https://www.ilna.ir/%D8%B5%D9%81%D8%AD%D9%87-%D8%AA%D8%B9%D8%B1%D9%81%D9%87-%D8%A2%DA%AF%D9%87%DB%8C-22`

\> `ilna.ir##[href^="/advertisements/"]`





> * وارد یکی از اخبار این سایت که بشید بعد از چند ثانیه بالای خبر یه تبلیغ ویدیویی بارگزاری میشه که البته با فیلتر `‎##.zxc` که گذاشتین پنهان میشه.
>   آیا از دانلود این ویدیوها جلوگیری هم میشه؟

لینک صفحه ای که توش اینو میبینید بفرستید. این فیلتر رو به My filters اضافه کنید و سپس از اون تبلیغ ویدیویی یه عکس بفرستید:

`ilna.ir#@#.zxc`

**Comment by sepehr-brj** [comment]
> لینک صفحه ای که توش اینو میبینید بفرستید. این فیلتر رو به My filters اضافه کنید و سپس از اون تبلیغ ویدیویی یه عکس بفرستید

الان فهمیدم اون فیلتر `‎||tavoos.net^$all` که گذاشتین جلوش رو میگیره.

اون گزینه logger که گفتین تازه پیدا کردم. برای گوشی باید از I am an   advanced user فعال بشه.

**Comment by MasterKia** [comment]
> اون گزینه logger که گفتین تازه پیدا کردم. برای گوشی باید از I am an advanced user فعال بشه.

با فعال کردن کدوم گزینه؟

**Comment by sepehr-brj** [comment]
> با فعال کردن کدوم گزینه؟

https://github.com/gorhill/uBlock/wiki/Advanced-settings#uipopupconfig
