### ISSUE TITLE
[Ad Report] s0ft98.ir new ads

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#23]
```
||file.soft98.ir/afrak7.az$image
||cdn.hostdl.com/assets/soft98.gif$image
||file.soft98.ir/webzi.az$image
```
تبلیغات جدید سافت ۹۸.

**Comment by MasterKia** [comment]
سپاس. اگه تغییری پیش اومد منو در جریان بذارید.

**Comment by chromer030** [comment]
بله حتما ، و همونطوری که این سایت بیشتر اذیت میکنه ما هم بیشتر حواسمون رو بهش جمع میکنیم.

با تشکر فراوان از شما.
