### ISSUE TITLE
[Ad Report] tabnakjavan.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#24]
این سایت یه سری تبلیغات با اندازه تقریبا بزرگ داره که توی پیج هاش نمایش داده میشن و نه صفحه اصلی :
```
‍‍‍||tabnakjavan.com/files/adv/475_172.gif
||tabnakjavan.com/files/adv/474_168.gif
||tabnakjavan.com/files/adv/201_269.gif
||tabnakjavan.com/files/adv/347_279.jpg
```

**Comment by MasterKia** [comment]
https://github.com/MasterKia/PersianBlocker/commit/cab263f025dbb39c518c037108dd2fdabe99eb72

**Comment by MasterKia** [comment]
سپاس از گزارش. درست شد.
