### ISSUE TITLE
Hide digikala sponsored products

### ISSUE THREAD

**Issue by mortezadadgar** [MasterKia/PersianBlocker#241]
Hi,
I'm sick of seeing sponsored products in digikala search results, they come with this element at the top-left of product 
![image](https://github.com/user-attachments/assets/5b8954d3-fdcb-4f53-9874-88e7d146c268)

**Comment by mortezadadgar** [comment]
بفرمایید https://www.digikala.com/search/?q=مثنوی%20معنوی

**Comment by mortezadadgar** [comment]
آره از ublock origin با فایرفاکس استفاده می کنم لاگین هم نکردم دیجیکالا

**Comment by Hoomansa78** [comment]
مثل این که دوباره داره نمایش داده میشه

<img width="1920" height="972" alt="Image" src="https://github.com/user-attachments/assets/12b215fc-accf-4b67-b878-3b530b19bbdb" />

و لینکی که داره این حالت رو داره
https://www.digikala.com/product/dkp-21372625/%D9%87%D8%AF%D9%81%D9%88%D9%86-%D8%B1%DB%8C%D9%88%D9%84%DB%8C%D9%86%DA%A9-%D9%85%D8%AF%D9%84-120-pro3/?ad_variant_id=80926940
انتهای آن ها همچین تگی داره

<img width="1306" height="50" alt="Image" src="https://github.com/user-attachments/assets/5de77def-8838-4ffb-9b0f-fc421c2a53af" />
