### ISSUE TITLE
too broad and too much blocking on alef.ir and isna.ir

### ISSUE THREAD

**Issue by rezad1393** [MasterKia/PersianBlocker#26]
this block list blocks indiscriminately and too broadly.
example:
`https://www.alef.ir/news/4010510021.html`
the picture of the article are blocked.
they are hosted at https://cdn.isna.ir
why would anyone block a cdn?

**Comment by MasterKia** [comment]
درود بر شما.


> this block list blocks **_indiscriminately and too broadly_**.

لطفاً‌ همه مواردی که حضور ذهن دارید و «بی قید و شرط و بیش از حد گسترده» مسدود شدن رو همینجا بفرستید تا بررسی و رفع اشکال کنم.





> example:
> `https://www.alef.ir/news/4010510021.html`
> the picture of the article are blocked.

فیلتری که باعث بروز این مشکل شده:

`||cdn.isna.ir/d/*?ts=$image`

این فیلتر برای مسدودسازی تبلیغات سایت ایسنا `isna.ir` به کار گرفته شده بود:
![Screenshot_20220801_134912](https://user-images.githubusercontent.com/17685483/182128162-034b570c-a0e5-4a2c-8334-6ec4edf2da4d.png)

الآن فیلتر رو به خود سایت ایسنا محدود میکنم تا دیگه روی سایت های دیگه همچین اثری نذاره.




> they are hosted at `https://cdn.isna.ir`
> why would anyone block a cdn?

چون هر cdn ای میتونه شامل تبلیغات باشه. اگه کل دامنه `cdn.isna.ir` رو مسدود میکردم اعتراضتون به‌جا می‌بود اما فقط بخشی از عکس های این دامنه رو مسدود کرده بودم نه کل دامنه رو.

**Comment by rezad1393** [comment]
usually only adservers get broad blocks.
not cdns.

**Comment by MasterKia** [comment]
> get broad blocks.

مسدود سازی «گسترده»:
`||cdn.isna.ir`

مسدودسازی «هدفمند و مشخص»:
`||cdn.isna.ir/ads_*.gif`

**Comment by MasterKia** [comment]
> this is just a suggestion.
not a دستور.

I understand. You are free to search for "cdn." in the list and suggest the cases you think are broad.

**Comment by rezad1393** [comment]
> > get broad blocks.
> 
> مسدود سازی «گسترده»:
> 
> `||cdn.isna.ir^`
> 
> مسدودسازی «هدفمند و مشخص»:
> 
> `||cdn.isna.ir/ads_*.gif`
> 
> مسدودسازی که به کار گرفته بودم از نوع دوم بود.

it was this  ||cdn.isna.ir/d/*?ts=$image
not this : `||cdn.isna.ir/ads_*.gif`

**Comment by MasterKia** [comment]
مثال مشخص تر زدم که قابل فهم تر باشه.

**Comment by rezad1393** [comment]
this is not your fault.
I see alot of these in russian ads too.
maybe just use the domain scope and limit them.
as you have done for fix.

**Comment by MasterKia** [comment]
So far I have only used first-party scope for exceptions (whitelists).

Examples from the list:
```
@@||asandl.com/ads/img/$image,1p
@@||blogfa.com/static/ads/$image,1p
@@||beytoote.com/ads/images_$image,1p
```

But for blocks I haven't used first-party scope because I assume some sites might use ads from another sites.
