### ISSUE TITLE
[Ad Report] mobo.news

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#27]
با درود فراوان.
با توجه به ترافیک بالای این سایت انتظار میره به مرور تبلیغات این سایت بیشتر شه.
فعلا این دو مورد در ابعاد متوسط هستن :
```
||cdn01.mobo.news/media/wp-content/uploads/2022/08/02122437/bitpin-584-98.gif
||cdn01.mobo.news/media/wp-content/uploads/2022/08/02122449/584-98.gif

```

**Comment by MasterKia** [comment]
>‌ انتظار میره به مرور تبلیغات این سایت بیشتر شه

بله درسته. همون ابتدا که این سایت راه‌اندازی شده بود من بهش سر زدم تا ببینم تبلیغی چیزی داره که مسدود بشه اما هنوز چیزی نذاشته بودن.
سپاس از گزارش.
