### ISSUE TITLE
Adaway سازگاری با

### ISSUE THREAD

**Issue by muctebanesiri** [MasterKia/PersianBlocker#276]
سلام 
من لیستو به adaway اضافه کردم ولی نتیجه‌ای نداشت. میخواستم بدونم لیست با adaway سازگاره یا نه؟ 

ایشوهای #184 و #185 در این خصوص بود ولی متوجه نشدم حقیقتش. 

با تشکر

**Comment by muctebanesiri** [comment]
ممنون. این ۲۶۹ هاست اضافه کرد. 
![Imagepipe_12.jpg](https://github.com/user-attachments/assets/65df5b8f-305d-450c-8789-bed4778add58)

فقط یه سوال. عموما بقیه فایل ها به دی ان اس 127.0.0.1 (لوکال هاست) میفرستن تبلیغاتو ولی این به 0.0.0.0. این مسئله که اثری روی بلاک تبلیغات نداره؟

مجددا ممنون

**Comment by muctebanesiri** [comment]
ممنون. این ۲۶۹ هاست اضافه کرد. 
![Imagepipe_12.jpg](https://github.com/user-attachments/assets/65df5b8f-305d-450c-8789-bed4778add58)

فقط یه سوال. عموما بقیه فایل ها به دی ان اس 127.0.0.1 (لوکال هاست) میفرستن تبلیغاتو ولی این به 0.0.0.0 این مسئله که اثری روی بلاک تبلیغات نداره؟

مجددا ممنون

**Comment by realartin** [comment]
درود
بزرگوار اپدیت نمیشه این لیست؟
