### ISSUE TITLE
soft98.ir

### ISSUE THREAD

**Issue by ahpourani** [MasterKia/PersianBlocker#28]
امکانش هست تو بروزسانی لیست لحاظ کنین، ممنون

جهت مشاهده لینک، افزونه حذف تبلیغات را در مرورگر غیرفعال و دکمه F5 را بزنید

**Comment by MasterKia** [comment]
درود بر شما.
دارم روش کار میکنم.
مدیر این سافت۹۸ هر روز عمداً‌ سایت خودش رو دستکاری میکنه تا فیلتر های ما رو دور بزنه.
ما هم هر روز استوارتر از دیروز پاسخش رو خواهیم داد.

**Comment by MasterKia** [comment]
مشکل حل شد. فیلتر PersianBlocker رو بروز کنید.
هر سری که این مشکل پیش اومد کافیه بهم بگید تا فوراً برطرفش کنم.
چون این سایت هر چند ساعت یکبار تغییرات میده بنابراین نیازه که اگه موردی دیدید گزارش کنید تا سریع و خشن برم سراغش.

**Comment by MasterKia** [comment]
شوربختانه فعلاً‌ باید لیست Quick fixes و uBlock Filters رو خاموش کنید تا سافت۹۸ درست کار کنه.
چون یه سری فیلتر های قدیمی توی اون لیستا هست.
یا صبر کنید تا اون لیست ها هم بروز بشن بعدش بهتون خبر میدم.

**Comment by ahpourani** [comment]
ممنونم از پیگیریتون شخصا هیچ مشکلی ندارم،
چون تو ۱۰۰ سایت برتر هستش برای کاربرای عادی، صرفا جهت اطلاع گفتم که تو آینده رفع بشه...

**Comment by MasterKia** [comment]
> چون تو ۱۰۰ سایت برتر هستش

اگه واقعاً همچین لیستی برای سایت های پارسی زبان وجود داره برام بفرستید.

**Comment by ahpourani** [comment]
لیست به روزی وجود نداره اما ابزارش هست من با similarweb چک میکنم رتبه سایت ها رو
ولی لیست اگر بخواین  ۵۰۰ سایت برتر از نظر الکسا تا پایان سال ۹۹ هست.
[https://gooyatech.com/top-sites-in-iran-by-alexa](url)

**Comment by MasterKia** [comment]
> یا صبر کنید تا اون لیست ها هم بروز بشن بعدش بهتون خبر میدم.

۱۰ دقیقه دیگه همه لیست های یوبلاک رو بروزرسانی کنید.

Filter lists => Purge all caches => Update now

**Comment by ahpourani** [comment]
ممنونم

**Comment by DRSDavidSoft** [comment]
Duplicate of #40.
