### ISSUE TITLE
https://wcity4.site/

### ISSUE THREAD

**Issue by aliafshany** [MasterKia/PersianBlocker#29]
سلام
اگر ممکن باشه بنر ها و تبلیغات اضافی هر صفحه رو که یکسان هستند رو هم در لیست قرار بدید.

ممنون

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/40741745/182921678-93ccb029-5c70-445c-be87-1cf4e647e95f.png">

در تصویر زیر هم تمامی این اسکرین شات اضافی هستند به جز اون باکس دانلود.
<img width="791" alt="image" src="https://user-images.githubusercontent.com/40741745/182921891-c9dd3ca5-ec51-4aff-bc85-2b2ae538494b.png">

**Comment by MasterKia** [comment]
درود بر شما.

میتونید این فیلتر ها رو به بخش "Custom Filters" یا "My filters" یا "User filters" افزونه مسدودسازتون اضافه کنید تا همه اون مواردی که اشاره کردید پنهان بشن:

```
wcity4.site##.dynamic_banner
wcity4.site##.fm-social-item:not(:has-text(پادکست))
wcity4.site##.su-note
wcity4.site##[href="https://plink.ir/fIHkI"]
wcity4.site##[href="https://www.instagram.com/wcityir"]
wcity4.site##[href="https://zaya.io/MovieWorld"]
wcity4.site##[href="https://idpay.ir/donatescofield"]
```

این موارد خود-تبلیغی (Self-Promotion) هستن یعنی سایت داره تبلیغِ‌ خودش رو میکنه و طبقِ قوانین EasyList (و طبعاً AdGuard) ما معمولاً‌ خود-تبلیغی ها رو مسدود/پنهان نمیکنیم.

**Comment by aliafshany** [comment]
عذرخواهی میکنم که این ایشو رو دوباره باز میکنم.
میخواستم بدونم که  لیست بالا رو چطوری بدست آوردید.

چون من با گزینه بلاک خود ادگارد که بلاک میکردم, صرفا خود اون صفحه بلاک میشد و نه صفحات دیگه.
اگر افزونه ای هست که بشه لینک ها رو اینطوری بدست آورد ممنون مشم که معرفی کنید.

**Comment by MasterKia** [comment]
@aliafshany 
https://tempsend.com/hycyh

خواستی فیلمو ذخیره اش کن چون بعد چند وقت خودکار پاک میشه.

**Comment by aliafshany** [comment]
ممنونم ازتون بابت دمو ویدیویی که گرفتید
البته کمی هم دانش CSS & HTML میخواست :)

تشکر

**Comment by MasterKia** [comment]
> البته کمی هم دانش CSS & HTML میخواست,

اگه بلد نباشید هم با آزمون و خطا پیدا میشه مورد درست رو پیدا کرد.
