### ISSUE TITLE
zibamoon.com

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#30]
تبلیغات این سایت:
```
||www.zibamoon.com/Files/Ads/
www.zibamoon.com##.MobileBannerArea
www.zibamoon.com##.NewsLetterPopupArea
www.zibamoon.com###RelatedContents
```
‏
- فیلتر `‎##.MobileBannerArea` برای حالت دسکتاپ صفحه اصلی، توی کامپیوتر هم عمل میکنه؟

‏
- فیلتر `‎##.NewsLetterPopupArea` هم برای خودتبلیغی مطالب سایته که بنظرم آزاردهنده هست.
‏<details><summary>اسکرین‌شات</summary>
![Screenshot_20220804-213430](https://user-images.githubusercontent.com/55192376/183061023-50b8e973-5efb-444c-9923-128ef3face4d.png)
‏</details>

‏
‏
یه سوال؛ این که فیلتر `/files/ads/` و `/files/adv/` رو برای تمام سایت‌ها نذاشتین دلیلی داره؟
‏

**Comment by MasterKia** [comment]
![Screenshot_20220805_154235](https://user-images.githubusercontent.com/17685483/183066050-0203d908-32e2-4522-8655-a47df471ac54.png)

توی گوشی به صورت پیشفرض فیلتر های عمومی اعمال نمیشن (گزینه "Ignore generic cosmetic filters").

**Comment by sepehr-brj** [comment]
پس چطور فیلترهای عمومی EasyList کار میکنن؟

**Comment by MasterKia** [comment]
توی گوشی کار نمیکنن. توی کامپیوتر کار میکنن.
توی گوشی هم میتونید گزینه‌اش رو فعّال کنید اما اگه گوشی رم یا پردازنده ضعیفی داره شاید روی سرعت بارگذاری صفحه ها اثر بذاره.

**Comment by sepehr-brj** [comment]
توی گوشی گزینه Ignore generic cosmetic filters پیشفرض فعاله. ولی فعال و غیرفعال بودنش اثری روی کار کردن این فیلتر توی EasyList نداره. در هر دو صورت فیلتر /files/ads/ کار میکنه.

**Comment by MasterKia** [comment]
بله اشتباه از من بود.
توی گوشی به صورت پیشفرض فیلتر هایی مثل "ads.##" کار نمیکنن.

**Comment by MasterKia** [comment]
> یه سوال؛ این که فیلتر `/files/ads/` و `/files/adv/` رو برای تمام سایت‌ها نذاشتین دلیلی داره؟

اونا رو به عهده EasyList و فیلتر های اصلی uBlock Origin میذاریم. چون اگه فیلتری باعث خرابی تو سایت ها بشه اونا زودتر گزارشش رو دریافت میکنن و یا میتونن حدس بزنن که این فیلتر نباید به صورت عمومی به کار بره.

**Comment by sepehr-brj** [comment]
خب کسی که از بریو استفاده میکنه تکلیفش چیه؟
باید به صورت دستی لیست EasyList رو هم اضافه کنه؟

**Comment by MasterKia** [comment]
اگه ندارتش آره،‌ ولی احتمال زیاد داره.

**Comment by sepehr-brj** [comment]
متاسفانه بریو فقط لیست EasyList Cookie رو داره

**Comment by MasterKia** [comment]
یه عکس از همه لیست هاش بفرستید.

**Comment by sepehr-brj** [comment]
```
Liste AR
Bulgarian Adblock list
EasyList China (中文)
CJX's Annoyance List
CJX's EasyList Lite (main focus on Chinese sites)
CZE, SVK: EasyList Czech and Slovak
EasyList Germany
Eesti saitidele kohandatud filter
Easylist-Cookie List - Filter Obtrusive Cookie Notices
Fanboy Annoyances List
Fanboy Social List
Finnish Addition to Easylist
AdGuard Français
Greek AdBlock Filter
Hufilter
ABPindo
Fanboy's India Filters
IRN: AdBlock Iran Filter
Icelandic ABP List
EasyList Hebrew
EasyList Italy
ABP X Files
Adguard Japanese filters (日本用フィルタ)
YousList
Fanboy's Korean
Adblock Plus Lithuania
EasyList Dutch
Dandelion Sprout's Nordic Filters
Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
Oficjalne Polskie Filtry Przeciwko Alertom o Adblocku
Oficjalne Polskie Filtry Przeciwko Alertom o Adblocku - Uzupełnienie
Romanian Ad (ROad) Block List Light
RU AdList (Дополнительная региональная подписка)
Adguard Russian Filter
BitBlock List (Дополнительная подписка фильтров)
EasyList Spanish
Adguard Spanish/Portuguese
Slovenian List
Frellwit's Filter List
EasyList Thailand
Adguard Turkish Filter
ABPVN List
uBlock Annoyances List (used with Fanboy Annoyances List)
```

**Comment by MasterKia** [comment]
https://github.com/brave/adblock-resources/blob/master/filter_lists/default.json#L60

**Comment by sepehr-brj** [comment]
ولی کار نمیکنه
فیلترش رو بخوام دستی امتحان کنم `‎||*/files/ads/*‎` میشه؟

**Comment by MasterKia** [comment]
`/files/ads/`
