### ISSUE TITLE
[Ad Report] Bartarinha.ir

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#31]
این سایت توی نسخه مبایلی اش ، اون پایین یه سری تبلیغات آزاردهنده رو نشون میده که مدام هم عوض میشن :

![Screenshot_20220806_163545](https://user-images.githubusercontent.com/13361552/183248270-8d327905-3882-4943-91d0-47524c089763.jpg)

**Comment by MasterKia** [comment]
درود بر شما.
لیست PersianBlocker رو دستی بروز کنید و با فایرفاکس اندروید بررسی کنید و ببینید درست شد؟
اگه درست نشده بود اطلاع بدید.

**Comment by chromer030** [comment]
لیست به روز شد ، با فایرفاکس اندروید تست شد ، مشکل برطرف شده ، تشکر فراوان از زحمات شما.

**Comment by MasterKia** [comment]
اگه تلگرام دارید بیزحمت ادتون رو موقتاً‌ باز کنید و آیدیتون رو برام بفرستید.

**Comment by chromer030** [comment]
بله حتما : https://t.me/RmDeu

**Comment by MasterKia** [comment]
ادتون بسته هست.

**Comment by chromer030** [comment]
باز شد.

**Comment by MasterKia** [comment]
انگار شماره مجازی دارید چون نمیتونم ادتون کنم.

https://t.me/joinchat/oeVYy-JampcyMmFk
بفرمایید.

**Comment by chromer030** [comment]
بله ، شماره مجازیه ، درخواست دادم.

**Comment by MasterKia** [comment]
حله،‌ اگه خواستی آیدی و بقیه پیام ها رو پاک کن. نخواستی هم هیچی.
