### ISSUE TITLE
[Ad Report] konkur.in

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#33]
انبوهی از تبلیغات بزرگ.

**Comment by MasterKia** [comment]
سپاس.

**Comment by sepehr-brj** [comment]
فقط همینا رو پیدا کردم:
(توی یکی از مطالب)

`konkur.in##.part-two-section` (فضای خالی اول صفحه)
`konkur.in##.vvv` (فضای خالی اول صفحه)
`konkur.in##.mobileBottomAd` (ضبدر چسبیده به پایین صفحه)

روی بریو تست نکردم
