### ISSUE TITLE
[Ad Report] iranmodares.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#34]
نسخه مبایل این سایت تبلیغات زیادی داره :

![Screenshot_20220806-182553](https://user-images.githubusercontent.com/13361552/183252614-9e9f2c4b-8b8d-4ebd-b075-ae77dcc1e4ce.png)

**Comment by MasterKia** [comment]
درود بر شما.
اینا به نظر خود-تبلیغی (Self-Promotion) باشه چون وقتی روی عکس کلیک میکنی لینکش داخل خود سایت میره.

**Comment by MasterKia** [comment]
اینا کارتون رو راه میندازه:

```
||iranmodares.com/baner/
iranmodares.com##.baner
```

**Comment by chromer030** [comment]
چک کردم ، درست میگید ، خود تبلیغی ان ، سپاس از شما.
