### ISSUE TITLE
پرسش و پاسخ

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#4]
چند مورد در حالت موبایل:

- ‏https://www.zoomit.ir
فضای خالی که توی اسکرین‌شات مشخص شده امتحان کردم اگه حذف بشه بنظرم زیباتر میشه
[اسکرین‌شات](https://user-images.githubusercontent.com/55192376/176109350-427dbf97-3a5f-416d-8e4b-62130259b391.png)
‏
‏
- ‏https://par30games.net
بنری که همیشه پایین صفحه میاد فقط توی دسکتاپ بلاک شده
[اسکرین‌شات](https://user-images.githubusercontent.com/55192376/176110654-a29d3adc-7337-4c28-86a9-eb8ad182ee6a.png)
‏
‏
- ‏https://www.kojaro.com
اینجا هم یه فضای خالی جا مونده
[اسکرین‌شات](https://user-images.githubusercontent.com/55192376/176111976-3259be92-4ed3-4416-90d4-8360377df281.png)
‏
‏
- ‏https://footballi.net
سایت فوتبالی بیشتر از بقیه سایت‌ها فضای خالی داره که جا مونده
[اسکرین‌شات1](https://user-images.githubusercontent.com/55192376/176113125-35fd11f5-5ee5-4d55-a016-77ee0abe0473.png)
[اسکرین‌شات2](https://user-images.githubusercontent.com/55192376/176113151-384c9526-f7e8-45c5-ab8f-f1dd450e7258.png)
[اسکرین‌شات3](https://user-images.githubusercontent.com/55192376/176113183-d186f3f1-061b-42d5-9d42-8bd974ce7852.png)
[اسکرین‌شات4](https://user-images.githubusercontent.com/55192376/176113190-8118e936-3bd5-4c5b-bc3d-d6c51bd7b7e5.png)

**Comment by MasterKia** [comment]
درود بر شما، سپاس از گزارش.
فیلتر ها رو من توی مرورگر کامپیوتر سرهم و تنظیم کردم و برای گوشی «هنوز» بهینه نشدن.
از یکی دو هفته دیگه بهینه کردن فیلتر ها برای مرورگر موبایل رو آغاز میکنم تا توی گوشی هم بتونید تجربه ای مشابه کامپیوتر داشته باشید.

از فایرفاکس اندروید استفاده میکنید؟ برای اطمینان میپرسم.

**Comment by MasterKia** [comment]
* فضای خالی برای زومیت رو پیدا نکردم؛ گفتید:

> * فضای خالی که توی اسکرین‌شات مشخص شده امتحان کردم اگه حذف بشه بنظرم زیباتر میشه

بیزحمت تگی که "امتحان" کردید و حذف شد رو برام بفرستید.



* برای par30games و kojaro و فوتبالی ردیف شد.

یه 5 تا 10 دقیقه دیگه لیست رو بروز بفرمایید و بررسی کنید اگه موردی بود نام سایت+عکس بفرستید تا پیگیری کنم.

**Comment by sepehr-brj** [comment]
> بیزحمت تگی که "امتحان" کردید و حذف شد رو برام بفرستید.

منم اولش نتونستم انتخابش کنم و مجبور شدم قبلش لیستتون غیرفعال کنم تا بتونم انتخابش کنم.
بجای تگ `zoomit.ir##.wide-adv-box` (لاین ۲۰۶۲) این تگ رو قرار بدین مشکل حل میشه:
`www.zoomit.ir##.top-landing-banner.wide-adv-row-home`

با عرض پوزش این تگ هم از سایت فوتبالی فراموش کردین:
`footballi.net##.ng-star-inserted.mediaad-row-top`

ممنون از زحماتتون ❤️
برای گزارش این تبلیغاتی که بلاک نمیشن به همین صورت توی ایشوی جدید گزارش کنیم یا یه ایشوی کلی برای این‌ها ایجاد میکنید تا اونجا اطلاع بدیم؟
و اینکه توی گزارشات فقط تگ‌ها رو قرار بدیم بهتره؟

**Comment by MasterKia** [comment]
> بجای تگ `zoomit.ir##.wide-adv-box` (لاین ۲۰۶۲) این تگ رو قرار بدین مشکل حل میشه:
> `www.zoomit.ir##.top-landing-banner.wide-adv-row-home`

`zoomit.ir##.wide-adv-row-home`

این باید خوب باشه.



> با عرض پوزش این تگ هم از سایت فوتبالی فراموش کردین:
> `footballi.net##.ng-star-inserted.mediaad-row-top`

افزوده شد، جالبه فقط `mediaad-top-row` رو لحاظ کرده بودم.



> ممنون از زحماتتون ❤️

خواهش میکنم. هر چه گزارش بیشتر، کیفیت لیست بالاتر.




> برای گزارش این تبلیغاتی که بلاک نمیشن به همین صورت توی ایشوی جدید گزارش کنیم یا یه ایشوی کلی برای این‌ها ایجاد میکنید تا اونجا اطلاع بدیم؟

اگه طبق سیستم لیست های بزرگ و معروف دیگه بخوام بگم، اونجا رسم و قانون این هست که برای هر سایت یه ایشوی جدید باز میکنن.

اما این لیست چون به اندازه اون لیست ها ایشو براش نمیاد شما هر طور که راحتید اقدام به گزارش کنید و میتونید _همینجا_، یا توی _ایشوی گفت و گو_، یا توی _ایشوی جدید_، یا هر جای دیگه که خواستید موارد جدید رو گزارش کنید.

اما در هر صورت ترجیح با "هر سایت، یک ایشوی جدید" هست.

> و اینکه توی گزارشات فقط تگ‌ها رو قرار بدیم بهتره؟

اگه وارد سایت شدید و موردی دیدید میتونید فقط مستقیماً همون رو گزارش کنید یعنی بیایید نشانی سایت+یه عکس بفرستید و تمام.

اما اگه زمان و توانش رو داشتید میتونید تگ مربوط به اون مورد رو هم پیوست کنید.

در کل هر چه فرایند گزارش دادن آسون تر باشه، طبیعتاً کاربرا هم احساس راحتی بیشتری برای گزارش دادن مشکلات میکنن و توی این لیست که به اندازه لیست های دیگه گزارش و فیدبک دریافت نمیکنه، گزارش بیشتر، پوئن مثبتیه.

**Comment by sepehr-brj** [comment]
> `zoomit.ir##.wide-adv-row-home`
> 
> این باید خوب باشه.

بله درست شد.
دیگه نیاز نیست که تگ قبلیش `zoomit.ir##.wide-adv-box` حذف شه؟
منظورم اینه که تگ‌های اضافی باعث نمیشن سایت‌ها دیرتر لود بشن؟ یا اهمیتی نداره؟

سایت فوتبالی یه مورد داره، توی حالت موبایل هِدِر سایت بعد از بلاک شدن تبلیغات ناپدید میشه و فقط یه فضای خالی نشون میده:
![Screenshot_20220709-103957_1](https://user-images.githubusercontent.com/55192376/178094447-bde3a4ac-0a66-4529-ac0c-344d774558b8.png)
![Screenshot_20220709-104100_1](https://user-images.githubusercontent.com/55192376/178094448-322697fc-6ba1-4b23-bb1d-5e28c0979b5e.png)

همیشه این مشکلو باهاش داشتم. میشه درستش کرد؟

**Comment by sepehr-brj** [comment]
‏@MasterKia 
خیلی عذر میخوام کامنت قبلیم رو ادیت کردم اگه میشه دوباره بخونیدش.
اون تگی هم که قبل از ادیت گفته بودم و حذف کردین الان بجاش باید تگ `zoomit.ir##.wide-adv-row` رو اضافه کنید تا دیگه بالای پست‌های سایت هم فضای خالی باقی نمونه.
بازم عذر میخوام وقتتون رو گرفتم.

**Comment by MasterKia** [comment]
خب اکنون ما برای محکم کاری هم `wide-adv-row` رو داریم و هم `wide-adv-row-home`.
اون سه تا فیلتری هم که دادید رو آزمایش کردم و کار کرد، با شرطِ `if env_mobile` تنظیم کردم تا اگه شخص توی موبایل بود اون سه تا فیلتر وارد عمل بشن (چون توی کامپیوتر اصلاً اون فیلتر ها کار نمیکنن و بنابراین نیازی بهشون نیست).

یه دلیل برای اینکه تا چند لحظه اول شما اون بخش هالی خالی رو می دیدید به نظر من میتونه به خاطر کمتر بودن سرعت پردازنده های گوشی باشه که یکم کندتر عمل میکنن.

یه دلیل دیگه اش هم ممکنه این باشه که من برای مسدود کردن تبلیغات زومیت فقط _یکدونه_ فیلتر گذاشتم که اون فیلتر میاد جلوی زومیت رو میگیره تا نتونه تبلیغات رو بخونه و بارگذاری کنه:.
کدِ زومیت:
```js
<script>var banner=JSON.parse('{"id":80153,"advertisements":[{"title":"بنر :: سامسونگ : نوت ۲۰: D1" ... </script>
```

راه حل من:
`zoomit.ir##+js(aopr, banner)`

* aopr یعنی [abort-on-property-read](https://github.com/gorhill/uBlock/wiki/Resources-Library#aoprjs-)

اما اگه از این راه حل هوشمندانه استفاده نمیکردم و صرفاً آدرس عکس تبلیغات و تگ تبلیغات رو مسدود میکردم شاید دیگه شما چند لحظه هم اون بخش های خالی رو نمی دیدید.

**Comment by MasterKia** [comment]
اون موردِ فوتبالی مورد جالب و عجیبیه، بررسی میکنم و خبر میدم.

**Comment by sepehr-brj** [comment]
دمتون گرم
من زیاد سر در نمیارم، خودتون هر طور که میدونید بهینه‌تره انجام بدین.
فقط میدونم این کارها وقت‌گیره و منم دوست دارم با این همه وقتی که میذارید کارتون بی‌نقص باشه.

**Comment by sepehr-brj** [comment]
سایت zoomg.ir هم دوتا فضای خالی داره توی پست‌هاش.
این توی دو حالت دسکتاپ و موبایل هست:
`www.zoomg.ir##.a1-banner.afterintro`

این یکی هم توی حالت موبایل:
`www.zoomg.ir###mobileBannerAfterTags`

نمیدونم باید جایگزین بشن یا فقط اضافه بشن.

اینم برای بنرهای بزرگ آدرس اینستاگرام و تلگرام که آخر تمام پست‌ها و قبل کامنت‌ها هستن:
`www.zoomg.ir##.beforesource`
نمیدونم اضافه کردن تگ‌های بنر‌های شبکه‌های اجتماعی به لیستتون درسته یا نه ولی برای من آزاردهنده‌ان اگر صلاح دونستید اضافه‌ش کنید.

**Comment by MasterKia** [comment]
ظاهراً مشکل از تداخل مقادیر CSS سایت فوتبالی هست. این دو فیلتر مشکل رو حل میکنه:
```
footballi.net##.ads-row
footballi.net##.mobile-header:style(top: 0 !important)
```
برای موبایل اضافه اش کردم.

**Comment by sepehr-brj** [comment]
> ظاهراً مشکل از تداخل مقادیر CSS سایت فوتبالی هست. این دو فیلتر مشکل رو حل میکنه:
> 
> ```
> footballi.net##.ads-row
> footballi.net##.mobile-header:style(top: 0 !important)
> ```
> 
> برای موبایل اضافه اش کردم.
> 
> 5 تا 10 دقیقه دیگه لیست رو بروز کنید.

دست مریزاد🤩
عالی شد👌

**Comment by MasterKia** [comment]
اون دو فیلتر افزوده شدن.
برای بنر شبکه های اجتماعی و دیگر مواردِ Self-Promotion (خود-تبلیغی، تبلیغ درباره خود) من طبق [سیاست های EasyList](https://easylist.to/pages/policy.html) (یکی از بزرگترین لیست های مسدودسازی تبلیغات که uBlock Origin هم از سیاست های اون پیروی میکنه)، بیان شده که "خود-تبلیغی ها نباید مسدود بشن، البته اگه به خاطر یه فیلتر دیگه ای غیرمستقیم مسدود شدن نباید از مسدودی درشون آورد".

طبق همین تصمیم گرفتم که موارد این چنینی مسدود نشن مگر اینکه خیلی رو مخ باشن (مثلاً چشمک زن باشن یا نصف صفحه رو بگیرن).

اما شما خودتون میتونید اون فیلتر رو توی بخش My filters داشته باشید و ازش بهره ببرید، ضمناً اگه توی فایرفاکس با حساب کاربریتون وارد شده باشید میتونید گزینه _Enable cloud storage support_ رو از تنظیمات uBlock Origin فعّال کنید که همه تنظیمات و فیلتر های شخصیتون توی حساب کاربریتون سینک بشن و بعداً از بین نرن.

**Comment by sepehr-brj** [comment]
الان متوجه شدم مشکلاتی که دیروز توی سایت‌های زومیت و زومجی برام پیش اومده‌بود بخاطر غیر فعال شدن فیلتر AdGuard Base بوده (تنظیمات uBlock رو به پیش‌فرض تغییر دادم و فیلتر AdGuard Base هم پیش‌فرض غیر فعاله).
به هر حال بنظرم این مشکلاتی که با فیلتر AdGuard Base درست میشن به لیست شما هم اضافه بشن بهتره.

**Comment by MasterKia** [comment]
اینجا پیشنهاد دادم که فیلتر های مربوط به سایت های پارسی زبان از لیست AdGuard Base حذف بشن:
`https://github.com/AdguardTeam/AdguardFilters/pull/121814`

قرار شد چند مدت بگذره و بعداً شاید حذف کنن.



> به هر حال بنظرم این مشکلاتی که با فیلتر AdGuard Base درست میشن به لیست شما هم اضافه بشن بهتره.

چه مشکلاتی؟

**Comment by sepehr-brj** [comment]
> چه مشکلاتی؟

همین فیلتر‌های زبان پارسی که توی AdGuard Base هستن و توی لیستتون نیست (البته نه همشون). مثل فیلتر‌هایی که دیروز برای سایت زومیت و زومجی اضافه کردین.

**Comment by sepehr-brj** [comment]
اون فیلتر `‎##.wide-adv-box` که یکی دیگه جایگزینش شد برای قسمت محصولات زومیت نیاز هست چون جای خالی میمونه. نمونه‌ش:
https://www.zoomit.ir/product/list/mobile

یه قسمت کوچک هم از تبلیغ چسبیده به پایین صفحه توی حالت موبایل پنهان نمیشه: (یکی از محصولات رو انتخاب کنید تا ببینیدش)
https://user-images.githubusercontent.com/55192376/180066070-bd145867-c3a7-41ed-815d-932af450dd32.png

**Comment by sepehr-brj** [comment]
> راستی لیست PersianBlocker به زودی به مرورگر Brave هم افزوده میشه.

بسیار عالی

نظرتون در مورد پنهان کردن رپورتاژهای آگهی چیه؟ بعضی سایت‌ها رپورتاژ‌های زیادی دارن که میتونه آزاردهنده باشه.

**Comment by MasterKia** [comment]
یه چند تا نمونه بفرستید بررسی کنیم.

مثلاً بخش خبر های تکنولوژی سایت سافت 98 رپورتاژ آگهی حساب میشه؟

**Comment by MasterKia** [comment]
یه چند تا نمونه بفرستید با هم بررسی کنیم.

البته چند تا از سایت هایی که توشون رپورتاژ آگهی بوده رو من قبلاً لحاظ کردم.

**Comment by sepehr-brj** [comment]
ریپورتاژهای زومیت استثنا هستن لطفا پنهانشون نکنید xD
نصف کامنت‌های زومیت و زومجی توی رپورتاژهاشون گذاشته میشه. کاربرها اونجا راجب موضوعات مختلف بحث میکنن و تعداد کامنت‌هاش به ۱۰۰ تا ۲۰۰ تا میرسه.

**Comment by MasterKia** [comment]
پنج صفحه اول زومیت رو نگاه کردم رپورتاژ های آگهی که گذاشتن، دیدگاه هاش انگشت شماره (زیر 5 تا):
```
https://www.zoomit.ir/pr/384428-sohaeshop/
https://www.zoomit.ir/pr/384411-payamtel/
https://www.zoomit.ir/pr/384389-dmway-events/
https://www.zoomit.ir/pr/384332-equipment-sadra-acomputer-conferencing-system/
```

**Comment by sepehr-brj** [comment]
آره خب پس مشکلی نداره زومیت
من دیدم رپورتاژهای زومجی اونطوریه فکر کردم زومیت هم همینطوره

**Comment by MasterKia** [comment]
بله زومجی انگار رپورتاژ هاش دیدگاه زیاد داره:
`https://www.zoomg.ir/pr/`

**Comment by sepehr-brj** [comment]
نسخه‌ی جدید زومیت هم روز ۶ شهریور منتشر میشه (احتمالا زومجی هم همین روز آپدیت کنن)

**Comment by MasterKia** [comment]
یعنی شاید چینش سایت (نام تگ های CSS) تغییر کنه؟

**Comment by sepehr-brj** [comment]
اطلاعی ندارم. فقط میگن علاوه بر قالب جدید امکانات جدیدی هم اضافه میشه.

**Comment by sepehr-brj** [comment]
فضای خالی تبلیغ بالای صفحه‌های دوم به بعد زومجی پنهان نمیشه.

میشه یه فیلتر CSS کلی برای هر سایت یا همه‌ی سایت‌ها ساخت؟
مثلا سه‌تا از فیلتر‌های زومیت با wide-adv شروع میشه، یا سه‌تا از فیلتر‌های زومجی با ads تموم میشه.

**Comment by MasterKia** [comment]
> میشه یه فیلتر CSS کلی برای هر سایت 

اگه منظورتون همچین چیزیه، بله شدنیه:
`zoomit.ir, zoomg.ir##.wide-adv-box`
> یا همه‌ی سایت‌ها ساخت؟

اگه منظورتون همچین چیزیه که روی همه سایت ها اثر بذاره:
`##.wide-adv-box`

این فیلتر های عمومی (Generic) رو گفتن که _**ترجیحاً**_ توی لیست های منطقه ای نباشه و در عوض توی لیستِ جامعِ EasyList قرار بگیره:
https://github.com/uBlockOrigin/uAssets/issues/14039#issuecomment-1186118648

> `##.ad-image`: such filters are for EasyList not for regional lists

**Comment by sepehr-brj** [comment]
منظورم اینه که برای سایت زومیت این سه‌تا فیلتر رو نمیشه یکی کرد؟
`##.wide-adv-box`
##.wide-adv-row
##.wide-adv-row-home

**Comment by MasterKia** [comment]
چرا میشه.
یه چیزی تو این مایه ها:

`zoomit.ir##[class^="wide-adv"]`

این فیلتر ها نیاز به پردازش توسط افزونه دارن یعنی افزونه باید بره همه تگ ها رو بگرده و تگ های موردنظر رو پیدا و پنهان کنه.
برای اینکه بار پردازشی اضافه وارد نکنیم چون تعداد فیلتر ها کم هستن به صورت دستی لحاظشون میکنیم.
اما اگه ۱۰ تا فیلتر wide-adv وجود داشت از همون یدونه فیلتر پردازشی استفاده میکردیم.

**Comment by sepehr-brj** [comment]
اون [حرکت انتحاری](https://github.com/MasterKia/PersianBlocker/issues/4#issuecomment-1179573071) که برای سایت فوتبالی زدین توی ادگارد عمل نمیکنه. ولی توی بریو اوکیه 👍
از این حرکت‌ها میشه توی سایت‌های دیگه هم زد؟ مثلا حالت دسکتاپ زومیت یه فضای خالی کنار کاشی‌ها میمونه.
https://user-images.githubusercontent.com/55192376/180829997-3ea4bbca-8da8-4ab2-8cf3-053ef99f2f71.png

میشه کاشی‌ها رو بزرگتر کرد یا اوردشون وسط؟

**Comment by MasterKia** [comment]
> توی ادگارد عمل نمیکنه

یعنی دقیقاً چه اتفاقی میفته؟



> از این حرکت‌ها میشه توی سایت‌های دیگه هم زد؟

بله. اگه CSS بلد باشی شدنیه.

**Comment by sepehr-brj** [comment]
> یعنی دقیقاً چه اتفاقی میفته؟

بعد از فعال کردن ادگارد هدر سایت هم پنهان میشه.

**Comment by sepehr-brj** [comment]
لیست رو توی ادگارد آپدیت کردم ولی درست نشده هنوز. (این تغییری که دادین برای حل مشکل توی ادگارد بود دیگه؟)
رپورتاژهای زومیت هم با ادگارد پنهان نمیشن.
اگه ادگارد توی عملکرد و بهینگی تفاوت زیادی با uBO داره بنظرم ارزشش رو نداره که دیگه لیست رو با ادگارد سازگار کنید.
هر وقت توضیحات رو آپدیت کردین حتما ذکر کنید که ادگارد به طور کامل از فیلتر‌های لیست پشتیبانی نمیکنه.
کلا نظرم راجب ادگارد عوض شد، این آخرین باری بود که ازش استفاده میکنم.

**Comment by MasterKia** [comment]
> مثلا حالت دسکتاپ زومیت یه فضای خالی کنار کاشی‌ها میمونه. https://user-images.githubusercontent.com/55192376/180829997-3ea4bbca-8da8-4ab2-8cf3-053ef99f2f71.png
> 
> میشه کاشی‌ها رو بزرگتر کرد یا اوردشون وسط؟ (با uBO یا هر افزونه‌ی دیگه)

`zoomit.ir##.showCaseWrapper:style(width: 100% !important;)`

**Comment by MasterKia** [comment]
> لیست رو توی ادگارد آپدیت کردم ولی درست نشده هنوز. (این تغییری که دادین برای حل مشکل توی ادگارد بود دیگه؟)

این فیلتر ها رو اگه به صورت دستی به بخش User filters ادگارد اضافه کنید کار میکنن:
```
footballi.net##.ads-row
footballi.net##.mobile-header:style(top: 0 !important)
```

**Comment by MasterKia** [comment]
> رپورتاژهای زومیت هم با ادگارد پنهان نمیشن.

اینو به صورت دستی اضافه کنید ببینید اثر داره یا نه:
`zoomit.ir##div[class^="item-list-row col-xs-"]:has(div>div>div>div>ul>li>a:has-text(آگهی))`

**Comment by sepehr-brj** [comment]
> `zoomit.ir##.showCaseWrapper:style(width: 100% !imimportant`

شما یه اسطوره‌اید

**Comment by sepehr-brj** [comment]
> این فیلتر ها رو اگه به صورت دستی به بخش User filters ادگارد اضافه کنید کار میکنن

من یک‌ماهی میشه که دیگه از ادگارد استفاده نمیکنم. فقط خواستم اطلاع داده باشم این موضوع رو. ولی اگه میخواید لیست رو با ادگارد هم سازگار کنید تست میکنم.

**Comment by MasterKia** [comment]
اگه ادگارد ندارید خودم آزمایش خواهم کرد.
ادگارد از نظر سازگاری نباید مشکل چشمگیری داشته باشه.
اما از نظر بهینگی، uBlock Origin ازش سرتره.

**Comment by sepehr-brj** [comment]
> اینو به صورت دستی اضافه کنید ببینید اثر داره یا نه:
> 
> `zoomit.ir##div[class^="item-list-row col-xs-"]:has(div>div>div>div>ul>li>a:has-text(آگهی))`

نه تاثیری نداشت.

**Comment by sepehr-brj** [comment]
> اگه ادگارد ندارید خودم آزمایش خواهم کرد. ادگارد از نظر سازگاری نباید مشکل چشمگیری داشته باشه. اما از نظر بهینگی، uBlock Origin ازش سرتره.

خب منم بعضی وقت‌ها تست میکنم و اگر مشکلی از ادگارد دیدم گزارش میدم.

**Comment by MasterKia** [comment]
فیلتر پنهان کردن رپورتاژ های زومیت رو جایگزین کردم، آزمایش کنید:

`zoomit.ir##.item-list-row:has(a[href*="/pr/"])`

**Comment by sepehr-brj** [comment]
> فیلتر پنهان کردن رپورتاژ های زومیت رو بهبود دادم و جایگزین کردم، اگه خواستید در ادگارد موبایل آزمایش کنید:
> 
> `zoomit.ir##.item-list-row:has(a[href*="/pr/"])`

ردیف شد

**Comment by MasterKia** [comment]
فیلتر قبلیه فقط از قسمت مطالب (که وسط صفحه بود) پنهان میکرد اما این جدیده هر جا رپورتاژ ببینه پنهان میکنه (گاهی سمت چپ توی مطالب جدید هم رپورتاژ میاد).

**Comment by sepehr-brj** [comment]
نسخه جدید سایت digiato.com منتشر شده.
مثل اینکه همون یه فیلتری که براش گذاشته بودین خوبه. 
اون فضاهای خالی هم که داره بنظرم بخاطر رابط کاربریش پنهان نشن بهتره.

**Comment by MasterKia** [comment]
سپاس از گزارش.


> اون فضاهای خالی هم که داره

فیلترش لحاظ شد.


بخش «تازه های امروز» هم برای دسکتاپ اندازه اش 100 درصد شد.

**Comment by sepehr-brj** [comment]
> بخش «تازه های امروز» هم برای دسکتاپ اندازه اش 100 درصد شد.

بسیار عالی.

این موضوع فضاهای خالی که بعد از پنهان شدن تبلیغات نمیتونستم درستشون کنم برام آزاردهنده بود. توی تبلت که حالت دسکتاپ سایت‌ها رو نشون میده بدتر هم به نظر میرسید.

با این فیلتر‌هایی که برای اندازه‌های المنت‌ها میذارین خیلی ظاهر سایت‌ها توی دسکتاپ و تبلت بهتر میشه دمتون گرم.

**Comment by MasterKia** [comment]
با این فیلتر های style خیلی کارا میشه کرد (بزرگ کردن اندازه متن، تغییر رنگ نوشته ها و ...)
کلا میشه CSS های سایت رو دستکاری کرد.

**Comment by MasterKia** [comment]
رپورتاژ های دیجیاتو هم باید پنهان بشن.

**Comment by sepehr-brj** [comment]
> رپورتاژ های دیجیاتو هم باید پنهان بشن.

بله.
خوبه که لینکشون هم جداست از بقیه پست‌ها و پیدا کردن فیلتر مناسبی که توی ادگارد هم عمل کنه باید راحت باشه.

**Comment by sepehr-brj** [comment]
سایت bama.ir ردیاب نداره؟

**Comment by sepehr-brj** [comment]
ممنون از شما.

لطفا این سایت هم بررسی کنید: www.radiofarda.com

**Comment by MasterKia** [comment]
این سایت از حوزه استحفاظی ما خارجه چون ردیاب های ایرانی نداره و فقط ردیاب های خارجی داره (که اونا هم با لیست های پیشفرض به درستی مسدود شدن).

**Comment by sepehr-brj** [comment]
### پیشنهاد
خیلی‌ها نمیدونن ادبلاکر چی هست و چرا باید ازش استفاده کرد.

نظرتون در مورد فعالیت در تلگرام و تهیه یه آموزش جامع استفاده از ادبلاکر و لیست شما به صورت Instant View چیه؟

با اجازه‌تون: t.me/PersianBlocker
‏commit ها توی کانال منتشر میشه.
یه گروه هم برای گزارش‌ها و پرسش‌ها برای راحتی کاربران.

برای دریافت گزارشات بیشتر و گسترش لیست میتونه جواب بده.
اگر موافق هستید و اجازه بدید حاضر به همکاری هستم.

**Comment by MasterKia** [comment]
درود بر شما.
مشکلی نیست انجام بدید. کار هاش با شما.

منم قصد دارم یه ایشو باز کنم و کسانی که قبلاً‌ در سه لیست پارسی زبان دیگه مشارکت میکردن رو دعوتشون کنم به مشارکت.

**Comment by sepehr-brj** [comment]
مشخص نیست چقدر طول میکشه تا لیستتون رو به بریو اضافه کنن؟

**Comment by MasterKia** [comment]
> مشخص نیست چقدر طول میکشه تا لیستتون رو به بریو اضافه کنن؟

https://github.com/brave/adblock-resources/pull/73

**Comment by sepehr-brj** [comment]
برای آپدیت کردن لیست هم باید VPN بزنیم 🤦‍♂
مثل اینکه raw.githubusercontent.com فیلتر شده.

**Comment by MasterKia** [comment]
رو همراه اول فیلتر نیست.
چند وقت پیش هم یه چند روز اون دامنه کار نمیکرد و به ظاهر مسدود بود اما بعدش درست شد.

**Comment by MasterKia** [comment]
نگاه کردم فیلتر نیست.
چند وقت پیش هم یه چند روز اون دامنه کار نمیکرد و به ظاهر مسدود بود اما بعدش درست شد.

**Comment by sepehr-brj** [comment]
برای من که نمیاد

‏shecan.ir هم میگه فیلتره:
![Screenshot_20220803-130526_1](https://user-images.githubusercontent.com/55192376/182563873-eaa1ac5a-ee1b-4090-9a6e-3aa6394c9530.png)

اینا کلا با عبارت "Hub" مشکل دارن

**Comment by MasterKia** [comment]
راه حل آسونی داره. خبر میدم.

**Comment by MasterKia** [comment]
https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L486

اینجا چهار تا لینک هست. به جز اولی، اون سه تا لینک دیگه رو آزمایش کنید و ببینید فیلتر هستن یا نه.

**Comment by sepehr-brj** [comment]
رفع فیلتر شد

> اینجا چهار تا لینک هست. به جز اولی، اون سه تا لینک دیگه رو آزمایش کنید و ببینید فیلتر هستن یا نه.

آره همه باز میشن

**Comment by MasterKia** [comment]
لینک اولی هم برای من مشکلی نداره. با DNS ای به جز DNS سرویس‌دهندتون آزمایش کنید.

**Comment by sepehr-brj** [comment]
آره نیم ساعت پیش رفع فیلتر شد
همون دی‌ان‌اس موزیلا که گفتین رو هم زدم

**Comment by MasterKia** [comment]
بله انگار فیلتر شده بوده.
حق با شما بود

https://instagram.com/stories/milad_nouri/2896519691580118296

**Comment by MasterKia** [comment]
تو گوشی هی دستم می‌خوره.

سپهر جان اد تلگرامت رو موقتاً باز کن و آیدیتو برام بفرست.

**Comment by sepehr-brj** [comment]
Losangelesguy

**Comment by MasterKia** [comment]
خواستی پاک کن

**Comment by sepehr-brj** [comment]
`zoomg.ir##.a1-banner`

فضای خالی تبلیغ توی پست‌های مطالب زومجی
