### ISSUE TITLE
[Ad Report] khabaronline.ir

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#41]
سلام و درود فراوان

```
||media.khabaronline.ir/d/2022/08/22/0/5733297.jpg?ts=1661148772000
||media.khabaronline.ir/d/2022/08/14/0/5730061.jpg?ts=1660490469000
||media.khabaronline.ir/d/2022/08/14/0/5730056.jpg?ts=1660490143000
||media.khabaronline.ir/d/2022/08/14/0/5730058.jpg?ts=1660490304000
```

**Comment by MasterKia** [comment]
درود و سپاس.

**Comment by sepehr-brj** [comment]
فیلترهای استایل حالت موبایل رو خراب میکنن.

فیلتر `‎###ads-container` رو فعال میکنید تا بخش «خواندنی ها» پنهان شه؟

**Comment by sepehr-brj** [comment]
فک کنم فقط برای موبایل میاد. تمام لینک‌هاش هم میره سایت‌های دگه.

<details><summary>تصویر</summary>

![Screenshot_20220920-095448](https://user-images.githubusercontent.com/55192376/191174567-131eb096-51d6-4b6e-a854-168d70db7205.png)

</details>
