### ISSUE TITLE
donya-e-eqtesad.com (media player)

### ISSUE THREAD

**Issue by ahpourani** [MasterKia/PersianBlocker#43]
خداقوت به شما با لیست خوبتون
یکی از سایت های خبری بود فکر کنم پلیر دامنه ثالث داشت که مثکه داخل لیست به عنوان تبلیغ شناسایی میشه و قابل لود شدن نیست بدون افزونه مشکل نداره ولی وقتی روشن باشه لود نمیشه.

`https://donya-e-eqtesad.com/بخش-سایت-خوان-62/3893712-رازگشایی-آذری-جهرمی-از-بلایی-که-سر-سرعت-اینترنت-در-ایران-می-آید-فیلم`

![Screen Shot 2022-08-26 at 1 29 19 AM](https://user-images.githubusercontent.com/87533149/186767785-55c85831-708f-4863-a9fc-d131862c620a.png)
.

**Comment by MasterKia** [comment]
درود و سپاس بابت گزارش خوبتون.
مشکل رفع شد.
