### ISSUE TITLE
[Ad Report] Pezeshket.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#45]
با درود فراوان.

```
||pezeshket.com/wp-content/uploads/2022/08/samim-new-14010601.gif
||pezeshket.com/wp-content/uploads/2022/08/samim-new-14010601-tail.gif
```

**Comment by MasterKia** [comment]
درود و سپاس.

**Comment by chromer030** [comment]
@MasterKia 
درود

تبلیغات جدید :

```
||pezeshket.com/wp-content/uploads/2023/02/22.png
##.code-block-7.code-block
```

![Screenshot_20230319_145453](https://user-images.githubusercontent.com/13361552/226172210-8dfd2293-ab11-450f-9c07-56b4fb589b38.jpg)
![Screenshot_20230319_145515](https://user-images.githubusercontent.com/13361552/226172216-5576e110-0a47-47ab-9bfa-5d5a07f4ff5b.jpg)


 Sample Page : https://pezeshket.com/%d9%85%d8%a7%d8%af%d8%b1-%d9%88-%da%a9%d9%88%d8%af%da%a9/fatigue-in-breastfeeding/

**Comment by chromer030** [comment]
درود 

```
||pezeshket.com/wp-content/uploads/2023/04/Ostrich-Oil-pezeshket.png
```
