### ISSUE TITLE
[Ad Report] arzcenter.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#48]
```
||media.arzcenter.com/media/files_None/nobitex.gif
```

با درود فراوان ، بعضی سایت ها که فقط یدونه تبلیغ دارن رو فقط به این دلیل گزارش میکنم که بیان توی دایره رصدمون و بعدها که تبلیغاتشون بیشتر شد ازشون سریع تر آگاه شیم.

**Comment by MasterKia** [comment]
درود و سپاس از گزارش.
هر موردی که به نظرتون ارزش گزارش داشت رو بفرستید،‌ حتی اگه تبلیغی هم نداشته باشن گاهی پیش میاد که مثل گزارش #47 یک ردیاب (`statsfa.com`) از توی سایت پیدا میشه.

**Comment by chromer030** [comment]
نظرتون چیه که Github Discussions رو باز کنید برای گزارش سایت های مشکوک و نیاز به بررسی ؟
توی Github Issues هم سایت هایی که قطعی ان و تبلیغات آشکار دارن رو گزارش کنیم برای اینکه هر سایت یه پیج برای موارد آتی داشته باشه.

**Comment by MasterKia** [comment]
انجام شد.
