### ISSUE TITLE
AdGuard Home Version

### ISSUE THREAD

**Issue by Monirzadeh** [MasterKia/PersianBlocker#5]
please add an [AdGuard Home](https://adguard.com/en/adguard-home/overview.html) version too.

**Comment by MasterKia** [comment]
درود بر شما.
آیا لیست PersianPiHole کارتون رو راه میندازه؟
https://github.com/MasterKia/PersianBlocker/raw/main/PersianPiHole.txt

تا یکی دو هفته دیگه لیست رو گسترش خواهم داد و سایت های بیشتری بهش اضافه خواهم کرد.

باید بگردم ریپوی مربوطه رو پیدا کنم و لیست PersianPiHole رو پیشنهاد کنم تا به AdGuard Home اضافه کنن.

**Comment by Monirzadeh** [comment]
> درود بر شما. آیا لیست PersianPiHole کارتون رو راه میندازه؟ https://github.com/MasterKia/PersianBlocker/raw/main/PersianPiHole.txt
> 
> تا یکی دو هفته دیگه لیست رو گسترش خواهم داد و سایت های بیشتری بهش اضافه خواهم کرد.
> 
> باید بگردم ریپوی مربوطه رو پیدا کنم و لیست PersianPiHole رو پیشنهاد کنم تا به AdGuard Home اضافه کنن.

https://github.com/AdguardTeam/AdguardFilters

**Comment by MasterKia** [comment]
اینجا پرسیدم ببینم چطور میشه لیست رو به AdGuard Home اضافه کرد:
https://github.com/AdguardTeam/FiltersRegistry/issues/617#issuecomment-1179179966

**Comment by MasterKia** [comment]
اینجا باید درخواست داد:
https://github.com/AdguardTeam/HostlistsRegistry


بعد از اینکه لیست Unwanted-Iranian از @DRSDavidSoft عزیز رو با PersianPiHole تجمیع کردم، بهشون درخواست میدم تا بررسی کنن.

**Comment by MasterKia** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/issues/59

**Comment by MasterKia** [comment]
> please add an [AdGuard Home](https://adguard.com/en/adguard-home/overview.html) version too.

@krystian3w Why the dislike? :p

**Comment by krystian3w** [comment]
Custom people can open issues directly into AdGuard with found free mother of Teresa from Kalkuta.

**Comment by Monirzadeh** [comment]
> Custom people can open issues directly into AdGuard with**out** found free mother of Teresa from Kalkuta on the Internet.

When I create issue, there is now any specific rule for AdGuard Home.
So no need of Mother Teresa.

**Comment by MasterKia** [comment]
منظورش چیه؟

**Comment by Monirzadeh** [comment]
> منظورش چیه؟

چیز مهمی نیست. می‌گه مستقیم در خود ریپوزیتوری AdGuard ثبت نکردی همه دنبال مادر ترزا (یک تیکه هم به هندی‌ها انداختند) هستند. من هم توضیح دادم که نسخه مخصوص adguard home برای این لیست موجود نبود. اگر باشد نیاز به اضافه شدن به خود AdGuard هم نیست. به همین دلیل ترجیج دادم با نگهدارنده پروژه مطرح کنم تا در آپدیت‌های آینده  adguard home را در صورت صلاحدید در نظر داشته باشند.
در‌نهایت چیزی که مهم است این است که اگر اسکریپتی برای تولید این لیست استفاده می‌کنید خروجی برای استفاده در adguard home هم بتواند تولید کند.
باقی حاشیه است.
در نهایت متشکر بابت تهیه و یکپارچه کردن لیست‌های دیگر.

**Comment by MasterKia** [comment]
@Monirzadeh 

سپاس بابت توضیحات، متوجه شدم.

**Comment by MasterKia** [comment]
@Monirzadeh 

نام PersianPiHole رو به PersianBlockerHosts تغییر دادم، چون احساس میکردم نام قبلی نشون میداد که این لیست فقط وابسته به PiHole هست.
آدرس جدید که باید جایگزین قبلی بکنید:
https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt


راستی لیست PersianBlocker به لیستِ جامعِ OISD افزوده شده و میتونید صرفاً لیست OISD رو فعّال داشته باشید:
https://oisd.nl/downloads
نسخه Full رو باید بگیرید.

**Comment by Monirzadeh** [comment]
متشکر.
