### ISSUE TITLE
[Ad Report] ejiga.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#50]
با درود فراوان.

این سایت مث اینکه یه جورایی موتور جستجوئه که زیر پست ها تبلیغات داره 

```
||www.ifilo.net/onclick/ads/d992754700504e4889d789d2d7c6f42d.jpg
||www.ifilo.net/onclick/ads/3097c352a95245d48e0687fdf6be2f0a.jpg
||www.ifilo.net/onclick/ads/1b4accfce655431fbeacd2b68cf1917b.jpg
||www.ifilo.net/onclick/ads/188ff157e25b4f8d85cb0f09c90c8ab2.png
```

**Comment by MasterKia** [comment]
درود و سپاس بی‌کران.

>‌ این سایت مث اینکه یه جورایی موتور جستجوئه

قبلاً که جستجو انجام می‌دادم زیاد به این سایت ها برخورد میکردم اما انگار نسلشون ورافتاده :-)
