### ISSUE TITLE
[Ad Report] jeyran.net

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#51]
با درود فراوان
این سایت توی هر پستش تبلیغات نسبتا بزرگی داره
```
||jeyran.net/wp-content/uploads/2018/01/290x290-1.gif
||jeyran.net/wp-content/uploads/2018/01/33d7a1bd-430d-4dea-ac96-d0b84f717eb5.gif
||jeyran.net/wp-content/uploads/2018/01/G10-290x290-2.gif
||jeyran.net/wp-content/uploads/2018/01/290-290.gif
||jeyran.net/wp-content/uploads/2021/12/4231.1-min*.jpg
||jeyran.net/wp-content/uploads/2021/12/4231.2-min*.jpg
```

**Comment by MasterKia** [comment]
درود و سپاس بسیار.
این سایت قفل کلیک راست و انتخاب متن هم داشت.

**Comment by chromer030** [comment]
دم شما گرم 👍

**Comment by sepehr-brj** [comment]
نمیدونم چرا فکر میکنم این سایت تغییر کرده.

فیلتر استایلی که گذاشتید یه مقدار جزئی روی حالت موبایل تاثیر منفی داره.
مقادیری که برای فیلتر استایل گذاشتید رو بذارید روی 100% مشکلی به وجود میاد؟

مثل اینکه پست‌های این سایت توی حالت دسکتاپ به فیلتر استایل نیاز دارن. یکیشون رو باز کنید ببینید.
