### ISSUE TITLE
[Ad Report] ifilo.net

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#53]
با درود
```
||www.ifilo.net/onclick/ads/5bbacc1f26bd4342b9771329e0f07df4.png
||www.ifilo.net/onclick/ads/873a4777810b41df85c4e97cdba9f7a5.png
||www.ifilo.net/onclick/ads/3097c352a95245d48e0687fdf6be2f0a.jpg
||www.ifilo.net/onclick/ads/188ff157e25b4f8d85cb0f09c90c8ab2.png
```

**Comment by MasterKia** [comment]
درود بر شما.
لیست رو بروز کنید و سپس از جایی که این تبلیغات رو می‌بینید عکس بدید.
و لینک اون صفحه رو هم بفرستید.

**Comment by chromer030** [comment]
[با این کامیت تبلیغات این سایت هم گرفته شد ، با تشکر](https://github.com/MasterKia/PersianBlocker/commit/8e1c5acecf119605feef8e360882a300af04350a)

**Comment by MasterKia** [comment]
یه مشکلی وجود داشت که رفع شد.
