### ISSUE TITLE
استفاده از لیست در مرورگر برومایت

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#6]
امکانش هست برای اضافه کردن لیست به [فیلتر مرورگر برومایت](https://www.bromite.org/custom-filters) راهنمایی کنید؟
با کمک [این ریپو](https://github.com/xarantolus/filtrite) هم لیست رو درست کردم ولی نمیدونم چرا کار نمیکنه.

**Comment by MasterKia** [comment]
درود بر شما.
در سایت [filterlists.010.one](https://filterlists.010.one) یک [جستجو](https://user-images.githubusercontent.com/17685483/178131182-26f71242-c3b3-47fe-af53-e496e37c1cad.png
) کردم و انگار یک نفر از قبل [یک لیست تجمیع شده برای سایت های پارسی زبان](https://github.com/IRBromiteFillterList/filtrite
) تشکیل داده.
میتونید این رو فعّال کنید:
https://github.com/IRBromiteFillterList/filtrite/releases/latest/download/bromite-iran-edit.dat

البته این لیست تجمیع شده، برگرفته از لیست های [Adblock-Iran](https://github.com/farrokhi/adblock-iran) و [uBOPa](https://github.com/nimasaj/uBOPa/) هست که لیست PersianBlocker تقریباً میتونه به جای هر دو تاشون استفاده بشه. 
من یک Pull Request برای اون ریپو میفرستم تا لیست PersianBlocker رو هم به لیست تجمیع شده اضافه کنن و یا جایگزین لیست های پارسی زبانِ دیگه بکنن.
فعلاً در این لحظه شما میتونید اون لیستی که فرستادم رو فعّال کنید تا ببینیم چی میشه.

**Comment by sepehr-brj** [comment]
ممنون. ولی باید لیست شما رو بجای اون دوتا لیست دیگه بذاره. الان چندتا سایت رو امتحان کردم باهاش فقط تبلیغات سایت ورزش۳ رو بلاک میکنه.

**Comment by MasterKia** [comment]
من لیست PersianBlocker رو در کنار لیست های دیگشون اضافه کردم اما پیشنهاد دادم که ترجیحاً لیست های دیگه حذف بشن و فقط یک لیست بمونه.
حالا مشکل فایرفاکس اندروید چی بود که به برومیت پناهنده شدید؟

**Comment by sepehr-brj** [comment]
مرورگر اصلی من برومایت بوده، تبلیغات سایت‌های فارسی مجبورم کرد که برم فایرفاکس (اون موقع ورژن 100 فایرفاکس اومده بود).

از ورژن 100 فایرفاکس تا الان (ورژن 102) که توی اندروید ازش استفاده کردم مشکلاتی داشته و درست نشدن. بزرگ‌ترینش کرش کردنه.

بخاطر همین میخوام برگردم به برومایت.

**Comment by MasterKia** [comment]
بعید بدونم مسدودساز برومیت بتونه به اندازه uBlock Origin انعطاف و قدرت داشته باشه (دنبال یه لینک درباره این موضوع میگشتم ولی نتونستم پیداش کنم).

**Comment by sepehr-brj** [comment]
خدا یه عقلی بده به گوگل
آخه مشکلش چیه که پشتیبانی از افزونه‌رو به کرومیوم اندروید اضافه نمیکنه تا کاربراش انقد به دردسر نیفتن

**Comment by MasterKia** [comment]
گوگل تا تقریباً یک سال دیگه پشتیبانی از افزونه های مسدودساز رو قراره تا حد زیادی حذف کنه و افزونه هایی مانند uBlock Origin کارایی خودشون رو از دست میدن.

البته الآن خیلی وقته که توی مرورگر Safari هم اوضاع به همین شکل هست.

تنها راه، پناه بردن به فایرفاکس (پیشنهاد من) و یا به مرورگر Brave (که مسدودساز داخلی داره و با لیست های uBlock Origin کار میکنه) هست.

**Comment by sepehr-brj** [comment]
لیست شما رو میشه توی مرورگر Brave فعال کرد؟

**Comment by MasterKia** [comment]
آزمایش کنید، من Brave ندارم.
اما قابلیت افزودن لیست رو داره:
https://brave.com/privacy-updates/10-custom-filter-lists

**Comment by krystian3w** [comment]
> البته الآن خیلی وقته که توی مرورگر Safari هم اوضاع به همین شکل هست.

IMO oldie Safari API is worse than new WebExetension.

**Comment by MasterKia** [comment]
> IMO oldie Safari API is worse than new WebExetension.

But I thought uBlock Origin did work with the old Safari API.

> Maybe works worse than latest ABP

That's what I assume, I think it supports network-only filters.

**Comment by MasterKia** [comment]
@krystian3w 

What is Adblock Plus opinion about Manfiest v3?

**Comment by MasterKia** [comment]
https://github.com/bromite/bromite/wiki/AdBlocking:

> Since v77 Bromite uses [Chromium subresource filter](https://github.com/chromium/chromium/tree/master/components/subresource_filter) and this engine _**does not currently support CSS rules**_; as a result some sites will show ads.

>  تبلیغات اگر بلاک‌هم بشن جای خالیشون میمونه.
بله درسته، موتور مسدودساز برومیت از فیلتر های CSS پشتیبانی نمیکنه و بنابراین "جایِ" تبلیغ ها پنهان نمیشن.

با این حال من [آموزش ساخت فیلتر برای برومیت](https://github.com/xarantolus/filtrite#using-your-own-filter-lists) رو پیدا کردم، اگه تونستم یه لیست براش میسازم.

**Comment by sepehr-brj** [comment]
> با این حال من آموزش ساخت فیلتر برای برومیت رو پیدا کردم، اگه تونستم یه لیست براش میسازم.

آره توی [کامنت اول ایشو](https://github.com/MasterKia/PersianBlocker/issues/6#issue-1299734910) همین جنریتر رو معرفی کردم و اولش فکر میکردم مشکل از جنریتر هست.

> آزمایش کنید و خبر بدید:
https://github.com/MasterKia/PersianBlockerBromite/releases/latest/download/PersianBlocker.dat

برای سایت‌هایی که خودم روزانه ازشون بازدید میکنم تقریبا تاثیری نداره. روزهای گذشته هم چندبار امتحان کردم.

> برومیت امکان افزودن چند لیست رو داره یا فقط یک دونه لیست میشه داشت؟

فقط یه لیست میشه بهش معرفی کرد.

چاره‌ای نیست دیگه از فایرفاکس استفاده میکنم.

**Comment by MasterKia** [comment]
> روزهای گذشته هم چندبار امتحان کردم.

چیو؟



> فقط یه لیست میشه بهش معرفی کرد.

اوکی



> چاره‌ای نیست دیگه از فایرفاکس استفاده میکنم.

گفتید بریو هم پشتیبانی میکنه که.

**Comment by sepehr-brj** [comment]
> چیو؟

مراحلی که همون جنریتر گفته رو انجام میدادم تا لیست شما رو برام درست کنه.

> گفتید بریو هم پشتیبانی میکنه که.

ادبلاکر بریو مشکلی نداره. از رابط کاربریش خوشم نمیاد. (از رنگ نارنجیش هم متنفرم)

**Comment by MasterKia** [comment]
کلاً بریو سیستم خنده داری داره.
تبلیغات سایت ها رو مسدود میکنه اما خودش از اون طرف تبلیغات نشون میده :)))))

https://brave.com/brave-rewards
> There are three kinds of Brave Ads: **sponsored images on new browser tabs**; **sponsored cards in the Brave News feed**; and infrequent **notifications that appear while you browse the web**.

**Comment by sepehr-brj** [comment]
چرا Firefox Nightly برای اندروید فقط توی پلی‌استور هست؟

**Comment by MasterKia** [comment]
نرم افزار F-Droid رو [بریزید](https://f-droid.org/F-Droid.apk) و سپس از داخلش نرم افزار [FFUpdater](https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/) رو بریزید.
از طریق اون میتونید همه نسخه های فایرفاکس رو دریافت و بروز کنید.

اگه نمیخوایید F-Droid بریزید، لینک مستقیم FFUpdater:
https://f-droid.org/repo/de.marmaro.krt.ffupdater_111.apk

**Comment by MasterKia** [comment]
راستی اگه F-Droid رو ریختید، نرم افزار RethinkDNS رو هم از توش نصب کنید.
نرم افزار خیلی خوبیه، DNS + Firewall.
میشه یه سری فیلترلیست ها رو از سمت گوشی (Client-Side) یا از سمت سرور (DNS-Side) فعّال کرد تا روی همه برنامه ها اعمال بشن، من از سمت سرور (DNS) فیلترلیست های مربوط به Privacy و فیلترلیست OISD (که شامل لیست PersianBlocker هم میشه) رو فعّال کردم.

اون قابلیت Firewall اش هم اجازه میده که دسترسی اینترنت همه برنامه های گوشی رو قطع کنی و فقط برنامه هایی که میخوای رو بهشون دسترسی اینترنت بدی.

**Comment by sepehr-brj** [comment]
ممنون از کمک‌هاتون ❤️

کاش آپدیت‌های Nightly فایرفاکس هم توی گیت‌هاب منتشر میشدن. من خیلی وقته عادت کردم به دانلود مستقیم اپ‌ها از گیت‌هاب.

آیا RethinkDNS نیاز به فعالسازی وی‌پی‌ان داره تا بتونه کارشو انجام بده؟

**Comment by MasterKia** [comment]
بله
