### ISSUE TITLE
[Ad Report] setare.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#62]
درود
```
||setare.com/files/1400/06/24/300x100.gif
||setare.com/files/1400/03/22/%D8%AA%D8%A8%D9%84%DB%8C%D8%BA%D8%A7%D8%AA-%D8%AF%D8%B1-%D8%B3%D8%AA%D8%A7%D8%B1%D9%87-300x250.jpg
```

**Comment by sepehr-brj** [comment]
اینا تازه اومدن؟

<details><summary>اسکرین‌شات‌ها</summary>

![Screenshot_20220914-225311](https://user-images.githubusercontent.com/55192376/190237518-9da89a23-df6f-478f-8e17-b24e57bf9f5f.png)
![Screenshot_20220914-225036_1](https://user-images.githubusercontent.com/55192376/190237549-8081ee18-3736-4812-9f12-51b5704247dc.png)
</details>

**Comment by chromer030** [comment]
این تبلیغات گزارش شدن ولی فیلتر نشدن
```
||setare.com/files/1400/06/24/300x100.gif
||setare.com/files/1400/03/22/%D8%AA%D8%A8%D9%84%DB%8C%D8%BA%D8%A7%D8%AA-%D8%AF%D8%B1-%D8%B3%D8%AA%D8%A7%D8%B1%D9%87-300x250.jpg
```

این یکی جدیده :
```
||setare.com/files/1401/06/20/728.90.gif
```

**Comment by sepehr-brj** [comment]
> درست شد،‌ سپاس. یه بررسی بکنید.

اوکی شد. ممنون.
