### ISSUE TITLE
Adguard Safari Rules "cinematicket.org"

### ISSUE THREAD

**Issue by ahpourani** [MasterKia/PersianBlocker#66]
خسته نباشین 
فیلترهایی که برای سایت `cinematicket.org` هستش با مرورگر chrome درست کار میکنه ولی رو safari ساختار سایت رو به هم میریزه. یه گپ سفیدی رو از بالای سایت تا لیست فیلم ها ایجاد میکنه.

https://user-images.githubusercontent.com/87533149/189165734-f3c463dc-318e-438a-9656-7041ccda139b.mp4

ممنون میشم یه بررسی بکنین.

**Comment by MasterKia** [comment]
درود بر شما.
من توی لیست نگاه کردم هیچ فیلتری برای سایت `cinematicket.org` نداریم.

**Comment by ahpourani** [comment]
ممنون از پیگیری
اشتباه از من بود ، بدون افزونه مسدود کننده هم همون مشکل رو داشت
