### ISSUE TITLE
[Ad Report] charbzaban.com

### ISSUE THREAD

**Issue by chromer030** [MasterKia/PersianBlocker#69]
درود
```
||charbzaban.com/wp-content/uploads/2021/10/afaq.gif
||charbzaban.com/wp-content/uploads/2021/04/zabanCompress-.gif
```

**Comment by MasterKia** [comment]
درود بر شما.
لینک صفحه‌ای که اینا توش هستن رو بفرستید،‌ من پیدا نکردم.

**Comment by chromer030** [comment]
http://charbzaban.com/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%B2%D8%A8%D8%A7%D9%86-%D8%A7%D9%86%DA%AF%D9%84%DB%8C%D8%B3%DB%8C/%D8%A7%D9%86%DA%AF%D9%84%DB%8C%D8%B3%DB%8C-%D9%85%D9%82%D8%AF%D9%85%D8%A7%D8%AA%DB%8C/%DB%8C%D8%A7%D8%AF%DA%AF%DB%8C%D8%B1%DB%8C-%D8%B3%D8%B1%DB%8C%D8%B9.html

![Screenshot_20220909_150557](https://user-images.githubusercontent.com/13361552/189331552-8b04e70b-a020-4421-bcdd-93caf87975cd.jpg)

**Comment by chromer030** [comment]
این دوتا هم هست :
```
||charbzaban.com/wp-content/uploads/2020/10/ielts-gama-min.gif
||charbzaban.com/wp-content/uploads/2021/10/gif-2-edited.gif
```

**Comment by MasterKia** [comment]
سپاس.
اون چهار تا تبلیغ که عکس ثابت بودن رو پنهان نکردم چون خیلی مزاحمتی ایجاد نمیکرد و سایت هم سایتِ‌ زبان هستش، بنابراین غیرمنطقی نیست که تبلیغ چند تا موسسه آموزش زبان رو بکنه (بدون ردیابی کاربران).
اما با این حال اگه دوستان توافق نظر دارن،‌ اون هم پنهان بشه.

**Comment by sepehr-brj** [comment]
اینو برای حالت موبایل بذارید:

`charbzaban.com##.at_bottom`

**Comment by sepehr-brj** [comment]
برای همین گفتم برای حالت موبایل بذارید.
