### ISSUE TITLE
shahrsakhtafzar.com

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#7]
تمام تبلیغات سایت shahrsakhtafzar.com با همین یدونه تگ بلاک میشه:
`www.shahrsakhtafzar.com##.flexbanneritem`

این تگ هم برای بنری که توی حالت موبایل به پایین صفحه چسبیده:
`www.shahrsakhtafzar.com##.mobile-fix-bottom.moduletable`

این دوتا هم برای فضای خالی اول پست‌ها(اونقدر بزرگ نیستن ولی توی موبایل به چشم میان) :
`www.shahrsakhtafzar.com###g-top`
`www.shahrsakhtafzar.com##.pishnahad.custom > p`

**Comment by MasterKia** [comment]
فیلتر `flexbanneritem` رو به جای `advert` اضافه کردم اما `ads2col` و `ads2colmobile` رو نگه داشتم چون یه بخش هایی رو پنهان میکنن (با خط قرمز مشخص شده):

https://user-images.githubusercontent.com/17685483/178131864-228bb8c6-642a-40c7-82d7-0f92199c37ed.png
https://user-images.githubusercontent.com/17685483/178131879-35a41060-040b-459e-999f-927c7878f7cb.png

فیلتر `pishnahad.custom > p` هم افزوده شد البته توی نسخه دسکتاپ به نظر میاد که میخواستن متنی چیزی اونجا بنویسن اما یادشون رفته و فقط یه "ر" نوشتن.
فیلتر `g-top` هم اضافه شد.

**Comment by sepehr-brj** [comment]
لطفا فیلتر `‎###logoads` رو اضافه کنید. مثل اینکه توی حالت دسکتاپ تاثیری نداره ولی برای موبایل نیازه.

فیلتر `‎##.pishnahad.custom > p` رو هم چک کنید انگار دیگه نیازی بهش نیست.

**Comment by sepehr-brj** [comment]
لطفا یه فیلتر هم برای رپورتاژهای این سایت بذارید.

https://www.shahrsakhtafzar.com/fa/news/pr/

**Comment by MasterKia** [comment]
۱۰ دقیقه دیگه لیست رو بروز بفرمایید و آزمایش کنید.

**Comment by sepehr-brj** [comment]
اوکیه
ممنون
