### ISSUE TITLE
gamefa.com

### ISSUE THREAD

**Issue by sepehr-brj** [MasterKia/PersianBlocker#8]
تگ فضای خالی بنر چسبیده به پایین صفحه که برای چند لحظه معلومه:
`gamefa.com###fix-advertise`

این تگ اضافی نیست؟
`gamefa.com##.fix-ads`

**Comment by MasterKia** [comment]
درود بر شما. سپاس از گزارش.

فیلتر `fix-advertise` افزوده شد.
فیلتر `fix-ads` رو نتونستم ببینم چیو پنهان میکنه ولی احتمالاً اون زمان که اضافه اش کردم تونسته بودم ببینم چه چیزی رو پنهان میکنه.
با این حال، فیلتر `fix-ads` داره یه چیزی رو پنهان میکنه چون uBlock Origin داره میگه من تگ fix-ads رو برات پنهان کردمش:
![image](https://user-images.githubusercontent.com/17685483/178137827-23d6f850-ecc4-4dfc-b685-e817ee3ec44b.png)

بنابراین فعلاً حذفش نمیکنم اما چند وقت دیگه اگه همچنان نتونستم ببینم چیو پنهان میکنه حذفش خواهم کرد.

**Comment by sepehr-brj** [comment]
ردیاب‌های سایت‌ها رو چطور پیدا کنیم و گزارش بدیم؟

**Comment by MasterKia** [comment]
توی یک سایت دلخواه برید، روی آیکن قرمز رنگ uBlock Origin کلیک کنید و پایین سمت چپ چند بار دکمه More رو بزنید تا بالاخره لیستی از یه سری آدرس ها نمایان بشه.
مثلاً برای آپارات:
![image](https://user-images.githubusercontent.com/17685483/178141903-7d0e0f5e-47ed-42c8-9802-cbfec6e06cfd.png)

هر آدرسی که اونجا نوشته اگه غیر از آدرس خود سایت باشه، پتانسیل ردیاب بودن رو داره.
مثلاً برای آپارات، صباویژن و enamad و ساماندهی آدرس هایی غیر از خودِ آپارات هستن؛ از بین این سه تا صباویژن ردیاب هست که منم قبلاً لحاظش کرده بودم و اگه سمت چپش رو ببینی قرمزه یعنی مسدود شده، اما اون دو تای دیگه ردیاب نیستن و صرفاً برای نشون دادن لوگوی اعتماد حضور دارن و بنابراین مسدودشون نکردم.

حالا یه نمونه دیگه؛ اگه برای سایت ورزش 3 رو نگاه کنیم، بین آدرس ها میشه سایت mediaad و یکتانت رو دید که خب جفتشون سایت تبلیغاتی/ردیابی هستن و من مسدودشون کرده بودم.

راه ساده اش اینه، راه یکم پیشرفته ترش اینه که روی آیکن uBlock Origin بزنی و دکمه سمت چپ چرخ دنده رو کلیک کنی تا Logger باز بشه، بعدش بری به سایت موردنظر. اینطوری همه درخواست های اون سایت رو میتونی ببینی (شامل درخواست هاش به سایت های ردیابی). من خودم اونطوری پیدا میکنم.

راه خیلی پیشرفته ترش اینه که دکمه F12 رو بزنی تا Developer Tools باز بشه و به زبونه Network بری تا همه درخواست های سایت رو ببینی و فقط ازونجاست که میتونی ببینی چه اطلاعاتی داره مخابره میشه (مثلاً آپارات داره دقیقاً _چه_ اطلاعاتی رو برای صباویژن میفرسته).

**Comment by sepehr-brj** [comment]
ممنون ❤️
